stages:
  - test
  - deploy

py36:
  image: python:3.6
  stage: test
  script:
    - pip install -r requirements.txt
    - sphinx-build -M linkcheck . _build

pages:
  image: python:3.6
  stage: deploy
  script:
    - pip install -r requirements.txt
    - sphinx-build -M html . _build
    - mv _build/html/ public/
  artifacts:
    paths:
      - public
  only:
    - master
